development:
  adapter: postgresql
  encoding: unicode
  database: lunch_panoply_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: lunch_panoply_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: lunch_panoply_production
  pool: 5

